# ==========================================
# 0. LOAD SECRETS (NEON DB URL)
# ==========================================
# This tells Spring to silently load the 'application-secret.properties' file
spring.profiles.include=secret

# ==========================================
# 1. SERVER CONFIGURATION
# ==========================================
server.port=8080

# ==========================================
# 2. POSTGRESQL (NEON DB) CONNECTION
# ==========================================
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# 3. JPA & HIBERNATE SETTINGS
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# 4. RABBITMQ CONNECTION (Docker)
# ==========================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest